import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Exo_2({
  weight: ["400", "700", "100", "300", "900", "500", "600", "800"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-clip">
      <body className={` ${font.className} overflow-x-clip bg-[#f0f0f0] `}>
        {children}
      </body>
    </html>
  );
}
